CREATE DATABASE IF NOT EXISTS CALENDAR;
USE CALENDAR;

CREATE TABLE IF NOT EXISTS USERS (
  ID int NOT NULL AUTO_INCREMENT,
  USERNAME varchar(220) DEFAULT NULL,
  PASS varchar(220) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS EVENTS (
  ID int NOT NULL AUTO_INCREMENT,
  DESCRIPTION_EVENT varchar(220) DEFAULT NULL,
  COLOR varchar(10) DEFAULT NULL,
  START_EVENT datetime DEFAULT NULL,
  END_EVENT datetime DEFAULT NULL,
  ID_USER int not null,
  FOREIGN KEY (ID_USER) REFERENCES USERS ( ID ),
  PRIMARY KEY (ID)
);

insert into events (DESCRIPTION_EVENT,COLOR,START_EVENT,END_EVENT,ID_USER)  values ("teste","#0071c5",STR_TO_DATE( "10/02/2021 10:00:00", "%d/%m/%Y %H:%i:%s" ),STR_TO_DATE( "01/05/2014 11:00:00", "%m/%d/%Y %H:%i:%s" ),1);

