CREATE DATABASE IF NOT EXISTS CALENDAR;
USE CALENDAR;
CREATE TABLE IF NOT EXISTS EVENTS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  DESCRIPTION_EVENT varchar(220) DEFAULT NULL,
  COLOR varchar(10) DEFAULT NULL,
  START_EVENT datetime DEFAULT NULL,
  END_EVENT datetime DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USERS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  USERNAME varchar(220) DEFAULT NULL,
  PASS varchar(220) DEFAULT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE EVENTS ADD CONSTRAINT FK_USER FOREIGN KEY ( ID ) REFERENCES USERS ( ID ) ;

